apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-with-dependency.fullname" . }}
  labels:
{{ include "helm-with-dependency.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-with-dependency.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}